# Generated by Django 4.0.8 on 2022-12-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_property_verification_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property_apply1',
        ),
    ]
